# coredns doesn't like references to nameservers on local loop back
# fix replaces `forward` with generic config pointing to google dns
# https://github.com/kubernetes/minikube/issues/7512#issuecomment-664348459
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
data:
  Corefile: |
    .:53 {
        errors
        health {
           lameduck 5s
        }
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
           pods insecure
           fallthrough in-addr.arpa ip6.arpa
           ttl 30
        }
        prometheus :9153
        hosts {
           192.168.49.1 host.minikube.internal
           fallthrough
        }
        cache 30
        loop
        reload
        loadbalance
        forward . 8.8.8.8 8.8.4.4
    }


